#!/bin/sh
cd source/

# Generates the automatic documentation of the api of the project
# See https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html for sphinx-apidoc options
# The paths that follows 'phinx-apidoc -o api ../..' are paths excluded from the generation
sphinx-apidoc -o api ../.. --force --separate --module-first

# Replace the autogenerated api/modules.rst with the content of _api-non-autogenerated-files/modules.txt
cat _api-non-autogenerated-files/modules.txt > api/modules.rst

# Remove lines 3-10 (both included) of the api/*.rst files of the packages (like apis or wrapper)
# This is done to remove the header of the submodules of those packages, avoiding the header to appear in the toctree
# The -i option is for removing those lines in the files
sed -i'.original' -e '3,10d' api/web_backend.apis.rst
sed -i'.original' -e '3,10d' api/web_backend.wrapper.rst
# Remove *.original files generated as backup by sed
rm api/*.original

# Generates the html files in the build folder
cd ..
make html
